// SDRAM.v

// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module SDRAM (
		input  wire        clk_clk,                               //                    clk.clk
		output wire        gpu_mem_master_0_debug_test_pass,      // gpu_mem_master_0_debug.test_pass
		output wire        gpu_mem_master_0_debug_test_fail,      //                       .test_fail
		output wire [3:0]  gpu_mem_master_0_debug_state_debug,    //                       .state_debug
		output wire [31:0] gpu_mem_master_0_debug_readback_debug, //                       .readback_debug
		input  wire        reset_reset_n,                         //                  reset.reset_n
		output wire        sdram_clk_clk,                         //              sdram_clk.clk
		output wire [12:0] sdram_controller_wire_addr,            //  sdram_controller_wire.addr
		output wire [1:0]  sdram_controller_wire_ba,              //                       .ba
		output wire        sdram_controller_wire_cas_n,           //                       .cas_n
		output wire        sdram_controller_wire_cke,             //                       .cke
		output wire        sdram_controller_wire_cs_n,            //                       .cs_n
		inout  wire [15:0] sdram_controller_wire_dq,              //                       .dq
		output wire [1:0]  sdram_controller_wire_dqm,             //                       .dqm
		output wire        sdram_controller_wire_ras_n,           //                       .ras_n
		output wire        sdram_controller_wire_we_n             //                       .we_n
	);

	wire         sys_sdram_pll_sys_clk_clk;                           // sys_sdram_pll:sys_clk_clk -> [gpu_mem_master_0:clk, mm_interconnect_0:sys_sdram_pll_sys_clk_clk, rst_controller:clk, sdram_controller:clk]
	wire  [31:0] gpu_mem_master_0_avalon_master_readdata;             // mm_interconnect_0:gpu_mem_master_0_avalon_master_readdata -> gpu_mem_master_0:avm_readdata
	wire         gpu_mem_master_0_avalon_master_waitrequest;          // mm_interconnect_0:gpu_mem_master_0_avalon_master_waitrequest -> gpu_mem_master_0:avm_waitrequest
	wire  [31:0] gpu_mem_master_0_avalon_master_address;              // gpu_mem_master_0:avm_address -> mm_interconnect_0:gpu_mem_master_0_avalon_master_address
	wire         gpu_mem_master_0_avalon_master_read;                 // gpu_mem_master_0:avm_read -> mm_interconnect_0:gpu_mem_master_0_avalon_master_read
	wire   [3:0] gpu_mem_master_0_avalon_master_byteenable;           // gpu_mem_master_0:avm_byteenable -> mm_interconnect_0:gpu_mem_master_0_avalon_master_byteenable
	wire         gpu_mem_master_0_avalon_master_readdatavalid;        // mm_interconnect_0:gpu_mem_master_0_avalon_master_readdatavalid -> gpu_mem_master_0:avm_readdatavalid
	wire         gpu_mem_master_0_avalon_master_write;                // gpu_mem_master_0:avm_write -> mm_interconnect_0:gpu_mem_master_0_avalon_master_write
	wire  [31:0] gpu_mem_master_0_avalon_master_writedata;            // gpu_mem_master_0:avm_writedata -> mm_interconnect_0:gpu_mem_master_0_avalon_master_writedata
	wire         mm_interconnect_0_sdram_controller_s1_chipselect;    // mm_interconnect_0:sdram_controller_s1_chipselect -> sdram_controller:az_cs
	wire  [15:0] mm_interconnect_0_sdram_controller_s1_readdata;      // sdram_controller:za_data -> mm_interconnect_0:sdram_controller_s1_readdata
	wire         mm_interconnect_0_sdram_controller_s1_waitrequest;   // sdram_controller:za_waitrequest -> mm_interconnect_0:sdram_controller_s1_waitrequest
	wire  [24:0] mm_interconnect_0_sdram_controller_s1_address;       // mm_interconnect_0:sdram_controller_s1_address -> sdram_controller:az_addr
	wire         mm_interconnect_0_sdram_controller_s1_read;          // mm_interconnect_0:sdram_controller_s1_read -> sdram_controller:az_rd_n
	wire   [1:0] mm_interconnect_0_sdram_controller_s1_byteenable;    // mm_interconnect_0:sdram_controller_s1_byteenable -> sdram_controller:az_be_n
	wire         mm_interconnect_0_sdram_controller_s1_readdatavalid; // sdram_controller:za_valid -> mm_interconnect_0:sdram_controller_s1_readdatavalid
	wire         mm_interconnect_0_sdram_controller_s1_write;         // mm_interconnect_0:sdram_controller_s1_write -> sdram_controller:az_wr_n
	wire  [15:0] mm_interconnect_0_sdram_controller_s1_writedata;     // mm_interconnect_0:sdram_controller_s1_writedata -> sdram_controller:az_data
	wire         rst_controller_reset_out_reset;                      // rst_controller:reset_out -> [gpu_mem_master_0:reset, mm_interconnect_0:gpu_mem_master_0_reset_reset_bridge_in_reset_reset, sdram_controller:reset_n]
	wire         sys_sdram_pll_reset_source_reset;                    // sys_sdram_pll:reset_source_reset -> rst_controller:reset_in0

	gpu_mem_master gpu_mem_master_0 (
		.clk               (sys_sdram_pll_sys_clk_clk),                    //         clock.clk
		.reset             (rst_controller_reset_out_reset),               //         reset.reset
		.avm_address       (gpu_mem_master_0_avalon_master_address),       // avalon_master.address
		.avm_read          (gpu_mem_master_0_avalon_master_read),          //              .read
		.avm_write         (gpu_mem_master_0_avalon_master_write),         //              .write
		.avm_writedata     (gpu_mem_master_0_avalon_master_writedata),     //              .writedata
		.avm_byteenable    (gpu_mem_master_0_avalon_master_byteenable),    //              .byteenable
		.avm_readdata      (gpu_mem_master_0_avalon_master_readdata),      //              .readdata
		.avm_waitrequest   (gpu_mem_master_0_avalon_master_waitrequest),   //              .waitrequest
		.avm_readdatavalid (gpu_mem_master_0_avalon_master_readdatavalid), //              .readdatavalid
		.test_pass         (gpu_mem_master_0_debug_test_pass),             //         debug.test_pass
		.test_fail         (gpu_mem_master_0_debug_test_fail),             //              .test_fail
		.state_debug       (gpu_mem_master_0_debug_state_debug),           //              .state_debug
		.readback_debug    (gpu_mem_master_0_debug_readback_debug)         //              .readback_debug
	);

	SDRAM_sdram_controller sdram_controller (
		.clk            (sys_sdram_pll_sys_clk_clk),                           //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),                     // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_controller_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_controller_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_controller_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_controller_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_controller_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_controller_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_controller_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_controller_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_controller_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_controller_wire_addr),                          //  wire.export
		.zs_ba          (sdram_controller_wire_ba),                            //      .export
		.zs_cas_n       (sdram_controller_wire_cas_n),                         //      .export
		.zs_cke         (sdram_controller_wire_cke),                           //      .export
		.zs_cs_n        (sdram_controller_wire_cs_n),                          //      .export
		.zs_dq          (sdram_controller_wire_dq),                            //      .export
		.zs_dqm         (sdram_controller_wire_dqm),                           //      .export
		.zs_ras_n       (sdram_controller_wire_ras_n),                         //      .export
		.zs_we_n        (sdram_controller_wire_we_n)                           //      .export
	);

	SDRAM_sys_sdram_pll sys_sdram_pll (
		.ref_clk_clk        (clk_clk),                          //      ref_clk.clk
		.ref_reset_reset    (~reset_reset_n),                   //    ref_reset.reset
		.sys_clk_clk        (sys_sdram_pll_sys_clk_clk),        //      sys_clk.clk
		.sdram_clk_clk      (sdram_clk_clk),                    //    sdram_clk.clk
		.reset_source_reset (sys_sdram_pll_reset_source_reset)  // reset_source.reset
	);

	SDRAM_mm_interconnect_0 mm_interconnect_0 (
		.sys_sdram_pll_sys_clk_clk                          (sys_sdram_pll_sys_clk_clk),                           //                        sys_sdram_pll_sys_clk.clk
		.gpu_mem_master_0_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                      // gpu_mem_master_0_reset_reset_bridge_in_reset.reset
		.gpu_mem_master_0_avalon_master_address             (gpu_mem_master_0_avalon_master_address),              //               gpu_mem_master_0_avalon_master.address
		.gpu_mem_master_0_avalon_master_waitrequest         (gpu_mem_master_0_avalon_master_waitrequest),          //                                             .waitrequest
		.gpu_mem_master_0_avalon_master_byteenable          (gpu_mem_master_0_avalon_master_byteenable),           //                                             .byteenable
		.gpu_mem_master_0_avalon_master_read                (gpu_mem_master_0_avalon_master_read),                 //                                             .read
		.gpu_mem_master_0_avalon_master_readdata            (gpu_mem_master_0_avalon_master_readdata),             //                                             .readdata
		.gpu_mem_master_0_avalon_master_readdatavalid       (gpu_mem_master_0_avalon_master_readdatavalid),        //                                             .readdatavalid
		.gpu_mem_master_0_avalon_master_write               (gpu_mem_master_0_avalon_master_write),                //                                             .write
		.gpu_mem_master_0_avalon_master_writedata           (gpu_mem_master_0_avalon_master_writedata),            //                                             .writedata
		.sdram_controller_s1_address                        (mm_interconnect_0_sdram_controller_s1_address),       //                          sdram_controller_s1.address
		.sdram_controller_s1_write                          (mm_interconnect_0_sdram_controller_s1_write),         //                                             .write
		.sdram_controller_s1_read                           (mm_interconnect_0_sdram_controller_s1_read),          //                                             .read
		.sdram_controller_s1_readdata                       (mm_interconnect_0_sdram_controller_s1_readdata),      //                                             .readdata
		.sdram_controller_s1_writedata                      (mm_interconnect_0_sdram_controller_s1_writedata),     //                                             .writedata
		.sdram_controller_s1_byteenable                     (mm_interconnect_0_sdram_controller_s1_byteenable),    //                                             .byteenable
		.sdram_controller_s1_readdatavalid                  (mm_interconnect_0_sdram_controller_s1_readdatavalid), //                                             .readdatavalid
		.sdram_controller_s1_waitrequest                    (mm_interconnect_0_sdram_controller_s1_waitrequest),   //                                             .waitrequest
		.sdram_controller_s1_chipselect                     (mm_interconnect_0_sdram_controller_s1_chipselect)     //                                             .chipselect
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (sys_sdram_pll_reset_source_reset), // reset_in0.reset
		.clk            (sys_sdram_pll_sys_clk_clk),        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),   // reset_out.reset
		.reset_req      (),                                 // (terminated)
		.reset_req_in0  (1'b0),                             // (terminated)
		.reset_in1      (1'b0),                             // (terminated)
		.reset_req_in1  (1'b0),                             // (terminated)
		.reset_in2      (1'b0),                             // (terminated)
		.reset_req_in2  (1'b0),                             // (terminated)
		.reset_in3      (1'b0),                             // (terminated)
		.reset_req_in3  (1'b0),                             // (terminated)
		.reset_in4      (1'b0),                             // (terminated)
		.reset_req_in4  (1'b0),                             // (terminated)
		.reset_in5      (1'b0),                             // (terminated)
		.reset_req_in5  (1'b0),                             // (terminated)
		.reset_in6      (1'b0),                             // (terminated)
		.reset_req_in6  (1'b0),                             // (terminated)
		.reset_in7      (1'b0),                             // (terminated)
		.reset_req_in7  (1'b0),                             // (terminated)
		.reset_in8      (1'b0),                             // (terminated)
		.reset_req_in8  (1'b0),                             // (terminated)
		.reset_in9      (1'b0),                             // (terminated)
		.reset_req_in9  (1'b0),                             // (terminated)
		.reset_in10     (1'b0),                             // (terminated)
		.reset_req_in10 (1'b0),                             // (terminated)
		.reset_in11     (1'b0),                             // (terminated)
		.reset_req_in11 (1'b0),                             // (terminated)
		.reset_in12     (1'b0),                             // (terminated)
		.reset_req_in12 (1'b0),                             // (terminated)
		.reset_in13     (1'b0),                             // (terminated)
		.reset_req_in13 (1'b0),                             // (terminated)
		.reset_in14     (1'b0),                             // (terminated)
		.reset_req_in14 (1'b0),                             // (terminated)
		.reset_in15     (1'b0),                             // (terminated)
		.reset_req_in15 (1'b0)                              // (terminated)
	);

endmodule
